name: dcli_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  dcli: ^3.1.0
  dcli_core: ^3.1.0
  file: ^6.1.4
  meta: ^1.10.0
  path: ^1.8.3
  scope: ^4.1.0
  stack_trace: ^1.11.1
  test: ^1.24.7
  uuid: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
